[project]
name = "opp-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
python = ">=3.8,<3.13"
package-mode = False
dependencies = [
    "streamlit>=1.44.1",
]
